@extends('layouts.app')
@section('title', 'Reports')
@section('content')
<div class="container section"><h1 class="h3 mb-3">Reports</h1>
<form class="card mb-3"><div class="card-body"><div class="row g-2"><div class="col-md-2"><input class="form-control" type="date" name="date_from" value="{{ request('date_from') }}"></div><div class="col-md-2"><input class="form-control" type="date" name="date_to" value="{{ request('date_to') }}"></div><div class="col-md-2"><select class="form-select" name="category_id"><option value="">Category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(request('category_id')==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="provider_id"><option value="">Provider</option>@foreach($providers as $provider)<option value="{{ $provider->id }}" @selected(request('provider_id')==$provider->id)>{{ $provider->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="booking_status"><option value="">Booking status</option>@foreach(['pending','confirmed','assigned','in_progress','completed','cancelled'] as $status)<option value="{{ $status }}" @selected(request('booking_status')===$status)>{{ $status }}</option>@endforeach</select></div><div class="col-md-1"><select class="form-select" name="payment_status"><option value="">Payment</option>@foreach(['pending','paid','failed'] as $status)<option value="{{ $status }}" @selected(request('payment_status')===$status)>{{ $status }}</option>@endforeach</select></div><div class="col-md-1"><button class="btn btn-brand w-100">Filter</button></div></div></div></form>
<div class="alert alert-success">Paid revenue in current page result set: KES {{ number_format($revenue) }}</div>
<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>No.</th><th>Service</th><th>Provider</th><th>Booking</th><th>Payment</th><th>Amount</th></tr></thead><tbody>
@foreach($bookings as $booking)<tr><td>{{ $booking->booking_number }}</td><td>{{ $booking->service->name }}</td><td>{{ $booking->provider->name ?? '-' }}</td><td>{{ $booking->status }}</td><td>{{ $booking->payments->last()->status ?? 'unpaid' }}</td><td>KES {{ number_format($booking->payments->last()->amount ?? $booking->estimated_price) }}</td></tr>@endforeach
</tbody></table></div></div><div class="mt-3">{{ $bookings->links() }}</div></div>
@endsection
